[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fourieroptics"
version = "0.1.0"
description = "Fourier optics propagation tools"
authors = [{name = "Dream"}]
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
